### ISSUE TITLE
Data seems to be stuck?

### ISSUE THREAD

**Issue by eddiejaoude** [dfm/osrc#162]
I have noticed data has not changed for a few days?

**Comment by floralvikings** [comment]
I've noticed the same thing; I recently moved a repository, so I thought that might be causing the problem.

**Comment by hellerve** [comment]
Nope, its because Github deprecated the Timeline API in favor of the Events API(1/1/2015). Seems like we should update that.

**Comment by dfm** [comment]
See #148.

**Comment by dfm** [comment]
I'm going to close this because it's a duplicate! Please comment on that thread if you have things to add. Thanks!
